### ISSUE TITLE
Coroutines processing is now only supported for pdo_odbc

### ISSUE THREAD

**Issue by zds-s** [hyperf/database-sqlserver-incubator#1]
![image](https://github.com/hyperf/database-sqlserver-incubator/assets/49744633/7f4304be-fcf7-468b-8356-3f2484f06b0e)
![image](https://github.com/hyperf/database-sqlserver-incubator/assets/49744633/176787a9-cbb9-4371-a3cb-694457ea276e)

**Comment by zds-s** [comment]
直接加个强验证吧。require 的时候就终止

**Comment by zds-s** [comment]
https://github.com/mineadmin/MineAdmin/actions/runs/8449502134/job/23143736007?pr=208

开了扩展还是报错

**Comment by zds-s** [comment]
@Chance-fyi

**Comment by Chance-fyi** [comment]
要配置 `odbc` 与 `odbc_datasource_name`

![image](https://github.com/hyperf/database-sqlserver-incubator/assets/37658940/631252ad-e978-4c1d-a20e-1a8d567c0903)

**Comment by zds-s** [comment]
@Chance-fyi  没看代码，这个能改成默认打开。name拼接的那种形式吗

**Comment by Chance-fyi** [comment]
> @Chance-fyi 没看代码，这个能改成默认打开。name拼接的那种形式吗

应该不行，必须配置 ODBC Driver

**Comment by zds-s** [comment]
DSN 里面配置了 database name ,host
还需要在配置项里面再配置一遍。感觉有点麻烦
@Chance-fyi

**Comment by Chance-fyi** [comment]
![image](https://github.com/hyperf/database-sqlserver-incubator/assets/37658940/12c02a67-8f79-436b-94fd-d70a9ef51fae)

可以这样配置，然后 `'odbc_datasource_name' => 'ODBC Driver 18 for SQL Server'` 就可以了

我之所以要这样配置

```php
'odbc_datasource_name' => 'DRIVER={ODBC Driver 18 for SQL Server};SERVER=db,1433;TrustServerCertificate=yes;database=test'
```

是因为我没有配置证书，会提示这个错误，然后没找到在 `/etc/odbcinst.ini` 配置 `TrustServerCertificate=yes` 的方法

```bash
SQLSTATE[08001] SQLConnect: -1 [unixODBC][Microsoft][ODBC Driver 18 for SQL Server]SSL Provider: [error:0A000086:SSL routines::certificate verify failed:self-signed certificate]
```

**Comment by zds-s** [comment]
![image](https://github.com/hyperf/database-sqlserver-incubator/assets/49744633/20cc9b98-2025-4152-a395-f6f98a8a0680)

DRIVER={ODBC Driver 18 for SQL Server};SERVER=mssql,1433;TrustServerCertificate=yes;database=mineadmin

**Comment by zds-s** [comment]
@Chance-fyi

**Comment by Chance-fyi** [comment]
不用 @ ，我 subscribe issues 了

Driver 你要看你的配置，`/etc/odbcinst.ini` 或者 `/etc/odbc.ini`
`odbcinst -q -s` 检查配置并输出配置的 Driver

**Comment by zds-s** [comment]
SQLSTATE[42000]: Syntax error or access violation: 8111 [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Cannot define PRIMARY KEY constraint on nullable column in table 'setting_config'. (SQLExecute[8111] at /home/runner/work/MineAdmin/MineAdmin/swoole/thirdparty/php81/pdo_odbc/odbc_stmt.c:253) (SQL: alter table "setting_config" add constraint "setting_config_key_primary" primary key ("key"))
